### ISSUE TITLE
Flavored Yogurt Reverts To Yogurt Starter

### ISSUE THREAD

**Issue by ArchiusPendragon** [l33tmaan/EFRecipes#23]
When cooking and utilizing fruit to flavor yogurt, it reverts to yogurt starter after storage.
This includes when it is cooked into meals, and stored in sealed crocks on shelves.

I believe this to be a bug, as it means you cannot reliably keep or store flavored yogurts.

**Comment by l33tmaan** [comment]
Hi there! This is intended, as otherwise it would just rot. I thought it would be nicer for it to turn back into starter that you can re-use to make more yogurt. That being said, maybe I could make yogurt last a little onger?

**Comment by Window-Hero** [comment]
That's actually a cool idea, but unfortunately it means that there's no way to extend the storage life of fruit yogurt.  Since it's a cure time not a spoil time it's not affected by:
1. temperature
2. cellar
3. foot spoilage rate world setting
4. crocks/sealed crocks
5. bottles
6. closed cauldrons
7. etc
If there was some way to make it affected by those, and still turn back into starter, that'd be really cool.
There is the added complication that fruit yogurt that has been turned into a meal will still cure into yogurt starter much faster than the meal will spoil, resulting in _funny yogurt_.
